[package]
name = "medic"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
clap_complete = { workspace = true }
indoc = { workspace = true }
medic-audit = { path = "../medic-audit" }
medic-doctor = { path = "../medic-doctor" }
medic-lib = { path = "../medic-lib" }
medic-shipit = { path = "../medic-shipit" }
medic-test = { path = "../medic-test" }
medic-update = { path = "../medic-update" }

[features]
# Treat warnings as a build error.
default = ["strict"]
strict = []

