[workspace]

members = [
    "medic",
    "medic-audit",
    "medic-check-asdf",
    "medic-check-hex",
    "medic-check-homebrew",
    "medic-check-npm",
    "medic-check-rust",
    "medic-doctor",
    "medic-init",
    "medic-lib",
    "medic-step-cargo",
    "medic-step-git",
    "medic-test",
    "medic-update",
]
