[workspace]

members = [
    "medic",
    "medic-check",
    "medic-check-asdf",
    "medic-check-hex",
    "medic-check-homebrew",
    "medic-check-npm",
    "medic-check-rust",
    "medic-doctor",
    "medic-init",
    "medic-lib",
    "medic-step",
    "medic-test",
]
