[workspace]

members = [
    "medic",
    "medic-audit",
    "medic-check-asdf",
    "medic-check-elixir",
    "medic-check-homebrew",
    "medic-check-npm",
    "medic-check-rust",
    "medic-doctor",
    "medic-init",
    "medic-lib",
    "medic-shipit",
    "medic-step-elixir",
    "medic-step-git",
    "medic-step-github",
    "medic-step-rust",
    "medic-test",
    "medic-update",
]
