[doctor]

checks = [
  { check = "asdf", command = "plugin-installed", args = { plugin = "rust" } },
  { check = "asdf", command = "package-installed", args = { plugin = "rust" } },
  { check = "homebrew" },
  { check = "rust", command = "crate-installed", args = { name = "cargo-audit" } },
  { check = "rust", command = "crate-installed", args = { name = "cargo-outdated" } },
  { check = "rust", command = "target-installed", args = { target = "aarch64-apple-darwin" } },
  { check = "rust", command = "target-installed", args = { target = "x86_64-apple-darwin" } },
]

[test]

checks = [
  { shell = { name = "Check for warnings", cmd = "cargo build --workspace --features strict" } },
  { step = { step = "cargo", command = "test" } },
]

[audit]

checks = [
  { shell = { name = "Audit crates", cmd = "cargo audit", allow_failure = true } },
  { check = { check = "cargo", command = "format-check" } },
  { step = { step = "cargo", command = "clippy" } },
]

