[doctor]
checks = [
  { check = "homebrew", output = "stdio" },
  { check = "tool-versions", command = "plugin-installed", args = { plugin = "rust" } },
  { check = "tool-versions", command = "package-installed", args = { plugin = "rust" } },
  { check = "rust", command = "crate-installed", args = { name = ["cargo-audit", "cargo-outdated"] } },
  { check = "rust", command = "target-installed", args = { target = ["aarch64-apple-darwin", "x86_64-apple-darwin"] } },
]

[test]
checks = [
  { name = "Check for warnings", shell = "cargo build --workspace --features strict --color always", verbose = true },
  { name = "Build for tests", shell = "cargo test --color always --no-run", verbose = true },
  [
    { name = "medic: tests", shell = "cargo test --color always --package medic", verbose = true },
    { name = "medic-audit: tests", shell = "cargo test --color always --package medic-audit", verbose = true },
    { name = "medic-doctor: tests", shell = "cargo test --color always --package medic-doctor", verbose = true },
    { name = "medic-init: tests", shell = "cargo test --color always --package medic-init", verbose = true },
    { name = "medic-lib: tests", shell = "cargo test --color always --package medic-lib", verbose = true },
    { name = "medic-outdated: tests", shell = "cargo test --color always --package medic-outdated", verbose = true },
    { name = "medic-run: tests", shell = "cargo test --color always --package medic-run", verbose = true },
    { name = "medic-shipit: tests", shell = "cargo test --color always --package medic-shipit", verbose = true },
    { name = "medic-audit: tests", shell = "cargo test --color always --package medic-audit", verbose = true },
    { name = "medic-test: tests", shell = "cargo test --color always --package medic-test", verbose = true },
    { name = "medic-update: tests", shell = "cargo test --color always --package medic-update", verbose = true },

  ],
]

[audit]
checks = [
  { name = "Audit crates", shell = "cargo audit --color always", verbose = true },
  { check = "rust", command = "format-check" },
  { name = "Check md format", shell = "bin/dev/format-md --check", remedy = "bin/dev/format-md --all" },
  { step = "rust", command = "clippy" },
]

[outdated]
checks = [
  { check = "rust", cd = "medic" },
  { check = "rust", cd = "medic-audit" },
  { check = "rust", cd = "medic-doctor" },
  { check = "rust", cd = "medic-init" },
  { check = "rust", cd = "medic-lib" },
  { check = "rust", cd = "medic-outdated" },
  { check = "rust", cd = "medic-run" },
  { check = "rust", cd = "medic-shipit" },
  { check = "rust", cd = "medic-src" },
  { check = "rust", cd = "medic-test" },
  { check = "rust", cd = "medic-update" },
]

[update]
steps = [
  { step = "git", command = "pull" },
  { doctor = {} },
]

[shipit]
steps = [
  { audit = {} },
  { update = {} },
  { test = {} },
  { name = "Release", shell = "bin/dev/release", inline = true },
  { step = "git", command = "push" },
  { step = "github", command = "link-to-actions", verbose = true },
]
