[doctor]

checks = [
  { check = "homebrew", output = "json" },
  { check = "tool-versions", command = "plugin-installed", args = { plugin = "rust" } },
  { check = "tool-versions", command = "package-installed", args = { plugin = "rust" } },
  { check = "rust", command = "crate-installed", args = { name = ["cargo-audit", "cargo-outdated"] } },
  { check = "rust", command = "target-installed", args = { target = ["aarch64-apple-darwin", "x86_64-apple-darwin"] } },
]

[test]

checks = [
  { name = "Check for warnings", shell = "cargo build --workspace --features strict" },
  { name = "Runt tests", shell = "cargo test", verbose = true },
]

[audit]

checks = [
  { name = "Audit crates", shell = "cargo audit", allow_failure = true, verbose = true },
  { check = "rust", command = "format-check" },
  { step = "rust", command = "clippy" },
]

[update]

steps = [
  { step = "git", command = "pull" },
  { doctor = {} },
]

[shipit]

steps = [
  { audit = {} },
  { update = {} },
  { test = {} },
  { name = "Release", shell = "bin/dev/release", verbose = true },
  { step = "git", command = "push" },
  { step = "github", command = "link-to-actions", verbose = true },
]
