on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build --workspace --features strict --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test --verbose

  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Use rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Install cargo audit
      uses: actions-rs/cargo@v1
      with:
        command: install audit
    - name: Cargo audit
      uses: actions-rs/cargo@v1
      with:
        command: audit
    - name: Cargo format check
      uses: actions-rs/cargo@v1
      with:
        command: fmt --check
    - name: Markdown format check
      run: cargo fmt --check
    - uses: PurpleBooth/gfmfmt-action@v2.0.14
      name: Check markdown formatting
    - name: Cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

